# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96b79f18297eaa046d713927e65080bb0e9c84a1c9681d2ca2151c7936b625ed671d8a9a6506aa75f3e10aa6116bc008b8d8d4d04e390695d876da4164586016

test:
  secret_key_base: 82a08676bef29b68cfb43f8413bebf29ef437030a11a81cecf8eb69dd70220b3315b57d95d6220e795f2d2c45891555821b871409aabc4e7f6f101ee5b369f0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
